name: Pre-commit
on:
  pull_request:

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        source $CONDA/bin/activate
        conda install -y conda-forge::pre-commit
    - name: Run pre-commit
      run: |
        source $CONDA/bin/activate
        pre-commit run --all-files
